/**
 * Builds the identifiers a field's parts reference each other by.
 */

/**
 * Describes the identifiers of the five elements a field wires together.
 */
export interface Ids {
  /**
   * Identifier of the control.
   */
  control: string;

  /**
   * Identifier of the counter.
   */
  counter: string;

  /**
   * Identifier of the error text.
   */
  errorText: string;

  /**
   * Identifier of the helper text.
   */
  helperText: string;

  /**
   * Identifier of the label.
   */
  label: string;
}

/**
 * Returns the five identifiers derived from one.
 *
 * @remarks
 *   The control takes the identifier unchanged, so a label outside the field can point at it with
 *   `htmlFor`. The others append a suffix: `-counter`, `-error`, `-helper` and `-label`.
 * @param id - The field's identifier, stated by the caller or generated by React.
 * @returns One identifier per element.
 */
export function idsOf(id: string): Ids {
  return {
    control: id,
    counter: `${id}-counter`,
    errorText: `${id}-error`,
    helperText: `${id}-helper`,
    label: `${id}-label`,
  };
}

/**
 * Returns the identifiers of the helper text and the error text, in that order, for an
 * `aria-describedby`.
 *
 * @remarks
 *   Both are listed whether or not each is rendered. Assistive technology skips an identifier that
 *   names no element, so the field does not track which parts exist. A checkbox, a switch and a
 *   fieldset read this value. A text control appends the counter's identifier.
 * @param ids - The field's identifiers.
 * @returns The space-separated identifiers.
 */
export function describedBy(ids: Ids): string {
  return `${ids.helperText} ${ids.errorText}`;
}
