/**
 * Publishes the vocabulary a recipe, a theme and an application are written in, and nothing that
 * runs in a browser. Every name here is read at build time. It is separate from the package's own
 * entry because that entry re-exports the generated runtime, and the compiler's configuration
 * reaches this package through whatever a theme imports: a theme importing the entry would put
 * every generated file behind the configuration, and regenerating them would read as the
 * configuration changing. The two attributes are published here as well as on the entry, so a
 * package that does not render, such as the testing kit, reads them without loading the provider
 * and its React transform.
 *
 * @packageDocumentation
 */

export { COLOR_MODE_ATTRIBUTE, THEME_ATTRIBUTE } from "#attributes.ts";
export { type Application } from "#authoring/application.ts";
export {
  BACKGROUNDS,
  BORDERS,
  contract,
  type ContractedVariant,
  type Family,
  type Filled,
  FOREGROUNDS,
  type Hue,
  type HuePalette,
  HUES,
  type Mode,
  type Moded,
  MODES,
  type Palette,
  type PaletteRoles,
  PALETTES,
  type Referenced,
  type Role,
  ROLES,
  type SemanticPalette,
  type Status,
  STATUSES,
  type ThemeColors,
  type ThemeTokens,
} from "#authoring/contract.ts";
export {
  contrast,
  type Level,
  linear,
  type Linear,
  luminance,
  oklab,
  type Oklab,
  readable,
} from "#authoring/contrast.ts";
export { type RecipeExtension, type SlotRecipeExtension } from "#authoring/extension.ts";
export { deepMerge } from "#authoring/merge.ts";
export {
  definePreset,
  type Preset,
  type PresetConfig,
  type PresetExtension,
  type Registrable,
} from "#authoring/preset.ts";
export {
  type Compound,
  compoundClassName,
  compoundSelection,
  defineRecipe,
  defineSlotRecipe,
  defineStyles,
  type Recipe,
  type RecipeProps,
  SEPARATOR,
  type SlotCompound,
  type SlotRecipe,
} from "#authoring/recipe.ts";
export {
  type Align,
  ALIGNMENTS,
  alignVariants,
  type Anatomy,
  below,
  columnCounts,
  CONTROL_INSET_END,
  CONTROL_INSET_START,
  controlSizes,
  cornerVariants,
  type Count,
  COUNTS,
  dense,
  DISTRIBUTIONS,
  divider,
  type Elevation,
  field,
  type Field,
  FIELDS,
  fieldStatusVariants,
  fieldVariants,
  filledColumns,
  fittedColumns,
  type Flat,
  FLATS,
  flatVariants,
  floating,
  gapSizes,
  type Highlight,
  HIGHLIGHTS,
  highlightVariants,
  iconOnly,
  iconSizes,
  insetSizes,
  interactive,
  type Justify,
  justifyVariants,
  type Lift,
  LIFTED,
  liftVariants,
  link,
  type Look,
  LOOKS,
  lookVariants,
  motion,
  type Motion,
  MOTIONS,
  motionVariants,
  onSlot,
  onSlots,
  overlay,
  ratioVariants,
  row,
  sizeVariants,
  slotsOf,
  spanCounts,
  statusEmitted,
  statusVariants,
  surface,
  tagSizes,
  textSizes,
  type Tone,
  TONES,
  toneVariants,
  touchTarget,
  truncate,
  type Weight,
  WEIGHTS,
  weightVariants,
  widthSizes,
} from "#authoring/recipes/index.ts";
export {
  defineTheme,
  type DerivedThemeConfig,
  type RootThemeConfig,
  type Theme,
  type ThemeConfig,
} from "#authoring/theme.ts";
// The style object a recipe's values are written in, published here so a recipe that builds a
// value by hand names the type without importing the runtime entry and the provider behind it.
export type { SystemStyleObject } from "#generated/types/system.d.mts";
export {
  type AnimationStyles,
  type LayerStyles,
  type SemanticTokens,
  type TextStyles,
  type Tokens,
} from "#pandacss.ts";
export {
  absoluteCenter,
  type AbsoluteCenterProps,
  bento,
  bentoCell,
  type BentoCellProps,
  type BentoProps,
  center,
  type CenterProps,
  cluster,
  type ClusterProps,
  cover,
  type CoverProps,
  type FixedStackProps,
  flex,
  type FlexProps,
  frame,
  type FrameProps,
  grid,
  type GridProps,
  hstack,
  reel,
  type ReelProps,
  responsive,
  scrollable,
  type ScrollableProps,
  sidebar,
  type SidebarProps,
  simpleGrid,
  type SimpleGridProps,
  stack,
  type StackProps,
  sticky,
  type StickyProps,
  switcher,
  type SwitcherProps,
  visuallyHidden,
  vstack,
} from "#patterns/index.ts";
export {
  alphaScale,
  backgrounds,
  BORDER_STEPS,
  borders,
  colorScale,
  controls,
  type Corner,
  CORNERS,
  drawn,
  families,
  type Families,
  fontSizes,
  FOREGROUND_STEPS,
  foregrounds,
  gaps,
  hues,
  icons,
  type Inked,
  inked,
  insets,
  mixed,
  neutralFills,
  oklch,
  type PageLightness,
  paletteAlias,
  type PaletteAliases,
  paletteRoles,
  palettes,
  type Palettes,
  radii,
  ramp,
  type Ratio,
  RATIOS,
  ROLE_SIZES,
  ROLE_STEPS,
  type RoleSteps,
  SCALE,
  type Scale,
  scaleOf,
  shadows,
  slides,
  type Solid,
  stated,
  type Step,
  stepOf,
  stepped,
  type Steps,
  surfaces,
  type SurfaceSteps,
  type TextRole,
  typography,
  type Width,
  WIDTHS,
  type Written,
} from "#scales/index.ts";
