/**
 * Publishes the vocabulary a recipe, a theme and an application are written in, and nothing that
 * runs in a browser. Every name here is read at build time. It is separate from the package's own
 * entry because that entry re-exports the generated runtime, and the compiler's configuration
 * reaches this package through whatever a theme imports: a theme importing the entry would put
 * every generated file behind the configuration, and regenerating them would read as the
 * configuration changing. The two attributes are published here as well as on the entry, so a
 * package that does not render, such as the testing kit, reads them without loading the provider
 * and its React transform.
 *
 * @remarks
 *   Three groups are published. A recipe author reads the definers, the helpers, the patterns
 *   and the contract. A theme author reads `defineTheme` and the parts of a statement. An
 *   application or a test that draws a palette of its own reads the engine and the measurements.
 * @packageDocumentation
 */

export { COLOR_MODE_ATTRIBUTE, THEME_ATTRIBUTE } from "#attributes.ts";
export { type Application } from "#authoring/application.ts";
export { type RecipeExtension, type SlotRecipeExtension } from "#authoring/extension.ts";
export {
  definePreset,
  type Preset,
  type PresetConfig,
  type PresetExtension,
  type Registrable,
} from "#authoring/preset.ts";
export {
  type Compound,
  compoundClassName,
  compoundSelection,
  defineRecipe,
  defineSlotRecipe,
  defineStyles,
  type Recipe,
  type RecipeProps,
  SEPARATOR,
  type SlotCompound,
  type SlotRecipe,
} from "#authoring/recipe.ts";
export {
  type Align,
  ALIGNMENTS,
  alignVariants,
  type Anatomy,
  type Axis,
  axis,
  below,
  columnCounts,
  CONTROL_INSET_END,
  CONTROL_INSET_START,
  controlSizes,
  cornerVariants,
  type Count,
  COUNTS,
  dense,
  DISTRIBUTIONS,
  divider,
  type Elevation,
  field,
  type Field,
  FIELDS,
  fieldStatusVariants,
  fieldVariants,
  filledColumns,
  fittedColumns,
  type Flat,
  FLATS,
  flatVariants,
  floating,
  gapSizes,
  type Highlight,
  HIGHLIGHTS,
  highlightVariants,
  iconOnly,
  iconSizes,
  insetSizes,
  interactive,
  type Justify,
  justifyVariants,
  type Lift,
  LIFTED,
  liftVariants,
  link,
  type Look,
  LOOKS,
  lookVariants,
  motion,
  type Motion,
  MOTIONS,
  motionVariants,
  onSlot,
  onSlots,
  overlay,
  ratioVariants,
  row,
  sizeVariants,
  slotsOf,
  spanCounts,
  statusEmitted,
  statusVariants,
  surface,
  tagSizes,
  textSizes,
  type Tone,
  TONES,
  toneVariants,
  touchTarget,
  truncate,
  type Weight,
  WEIGHTS,
  weightVariants,
  widthSizes,
} from "#authoring/recipes/index.ts";
export {
  defineTheme,
  type DerivedAxes,
  type DerivedColors,
  type DerivedStatement,
  type Looks,
  type RootStatement,
  type Theme,
  type ThemeStatement,
} from "#authoring/theme.ts";
export {
  BACKGROUNDS,
  BORDERS,
  CODE,
  type Code,
  type Families,
  type Family,
  type Filled,
  FOREGROUNDS,
  type Hue,
  type HuePalette,
  HUES,
  type Mode,
  type Moded,
  MODES,
  type Palette,
  type PaletteRoles,
  PALETTES,
  type Referenced,
  type Role,
  ROLES,
  type SemanticPalette,
  type Status,
  STATUSES,
  type ThemeColors,
  type ThemeTokens,
} from "#contract.ts";
export {
  alphaScale,
  ASPECT_RATIOS,
  atChroma,
  type Axes,
  type BodyRole,
  canonical,
  coded,
  type Colors,
  colorScale,
  contrast,
  type Corner,
  CORNERS,
  type Depth,
  depth,
  drawAxes,
  drawColors,
  type Drawn,
  drawn,
  type DrawnRoot,
  type DrawOptions,
  type Faces,
  faces,
  FLOOR,
  fontSizes,
  FOUNDATION,
  HAIRLINES,
  type HeadingRole,
  hues,
  inGamut,
  type Inked,
  inked,
  type Intents,
  intents,
  isDark,
  type LabelRole,
  type Ladder,
  ladderOf,
  type Level,
  lightened,
  lightnessOf,
  linear,
  type Linear,
  luminance,
  type Metrics,
  metrics,
  mixed,
  oklab,
  type Oklab,
  oklch,
  type Pace,
  PAGES,
  polar,
  type Polar,
  radii,
  RAMPS,
  type Ratio,
  type Ratios,
  RATIOS,
  ratiosOf,
  readable,
  referenced,
  ROLE_SIZES,
  type Roles,
  roles,
  type RootAxes,
  SCALE,
  type Scale,
  scaleOf,
  shadows,
  type Shape,
  shape,
  type Side,
  sideOf,
  slides,
  type Solid,
  stated,
  STATUS_HUES,
  stepOf,
  type Stroke,
  strokes,
  type Tempo,
  tempo,
  type TextRole,
  type Type,
  typeScale,
  type TypeScale,
  typography,
  type Width,
  WIDTHS,
  type Written,
} from "#draw/index.ts";
// The style object a recipe's values are written in, published here so a recipe that builds a
// value by hand names the type without importing the runtime entry and the provider behind it.
export type { SystemStyleObject } from "#generated/types/system.d.mts";
export {
  type AnimationStyles,
  type LayerStyles,
  type SemanticTokens,
  type TextStyles,
  type Tokens,
} from "#pandacss.ts";
export {
  absoluteCenter,
  type AbsoluteCenterProps,
  bento,
  bentoCell,
  type BentoCellProps,
  type BentoProps,
  center,
  type CenterProps,
  cluster,
  type ClusterProps,
  cover,
  type CoverProps,
  type FixedStackProps,
  flex,
  type FlexProps,
  frame,
  type FrameProps,
  grid,
  type GridProps,
  hstack,
  reel,
  type ReelProps,
  responsive,
  scrollable,
  type ScrollableProps,
  sidebar,
  type SidebarProps,
  simpleGrid,
  type SimpleGridProps,
  stack,
  type StackProps,
  sticky,
  type StickyProps,
  switcher,
  type SwitcherProps,
  visuallyHidden,
  vstack,
} from "#patterns/index.ts";
